### ISSUE TITLE
Add a README to current packages

### ISSUE THREAD

**Issue by Gejsi** [Gejsi/Material#20]
We have created a bunch of packages but they still don't have a **README** which should be available for all of them.
It's important for the user but even for us since it will help us remember every feature.
We will have to create a new PR for current packages to add the **README**.

**Comment by LucaT1** [comment]
We should first define a README template. This should be worked out in a separate PR, followed by a new PR for each component's readme.

Try to do some tests and then open a pull request on a new branch. I'll check it out and together we'll pull out a decent template for our packages' readme!

**Comment by LucaT1** [comment]
Working on it in> #21
